# =============================================================================
# Project 6 - C4.5 Decision Tree, Random Forest, and AdaBoost (OvR)
#
# # This file implements:
#   1. Single C4.5 Decision Tree
#   2. Random Forest using C4.5 Trees
#   3. AdaBoost using One-vs-Rest strategy for MNIST

import numpy as np
import matplotlib.pyplot as plt
import time
import os
import sys
import functools

from concurrent.futures import ProcessPoolExecutor



# =============================================================================
# OUTPUT LOGGING
# =============================================================================

class Tee:
    """
    Write output to multiple streams at the same time.

    This allows all existing print() statements to continue appearing in the
    terminal while also being saved to a text file.
    """

    def __init__(self, *streams):
        self.streams = streams

    def write(self, text):
        for stream in self.streams:
            stream.write(text)
            stream.flush()

        return len(text)

    def flush(self):
        for stream in self.streams:
            stream.flush()

    def isatty(self):
        return any(
            getattr(stream, "isatty", lambda: False)()
            for stream in self.streams
        )


def save_print_output(filename):
    """
    Decorator that saves every print() generated by a function and any
    functions it calls.

    Output is written to both:
      1. The terminal
      2. The specified text file

    The output file is overwritten each time the decorated function runs.
    """

    def decorator(function):
        @functools.wraps(function)
        def wrapper(*args, **kwargs):
            original_stdout = sys.stdout

            with open(filename, "w", encoding="utf-8") as log_file:
                sys.stdout = Tee(original_stdout, log_file)

                try:
                    print("=" * 80)
                    print(f"Saved output for: {function.__name__}")
                    print(f"Output file: {filename}")
                    print("=" * 80)
                    print()

                    return function(*args, **kwargs)

                finally:
                    print()
                    print("=" * 80)
                    print(f"End of saved output for: {function.__name__}")
                    print("=" * 80)

                    sys.stdout = original_stdout

        return wrapper

    return decorator


# =============================================================================
# SECTION 1 - DATA LOADING FUNCTIONS
# =============================================================================

# The following code loads the MNIST training and test datasets
def load_images(filename):
    # Open binary file
    with open(filename, 'rb') as f:
        # Read all bytes after the first 16-byte header
        data = np.frombuffer(f.read(), np.uint8, offset=16)
    
    # Reshape into:
    # (#images, 28, 28)
    return data.reshape(-1, 28, 28)

def load_labels(filename):
    with open(filename, 'rb') as f:
        data = np.frombuffer(f.read(), np.uint8, offset=8)
    return data


# =============================================================================
# SECTION 2 - DATA PREPROCESSING
# =============================================================================
# -----------------------------------------------------------------------------
# Original pixel values: 0 -> 255
# If we allow all 256 values:
#   Each decision node could create 256 branches
# This becomes:
#   - extremely slow
#   - memory expensive
#   - prone to overfitting
# Instead:
#   pixel < threshold  -> 0
#   pixel >= threshold -> 1
# This dramatically simplifies the tree.
# -----------------------------------------------------------------------------

def binarize_images(images, threshold=128):

    return (images >= threshold).astype(np.uint8)

# -----------------------------------------------------------------------------
# FLATTEN IMAGES
# Trees expect tabular data:
# BEFORE: (60000, 28, 28)  AFTER: (60000, 784)
# Each image becomes one row and each pixel becomes one feature.
# -----------------------------------------------------------------------------

def flatten_images(images):

    return images.reshape(images.shape[0], -1)

# -----------------------------------------------------------------------------
# Convert continuous numeric features into discrete bins.
# This is useful for the extra dataset because C4.5 is naturally designed
# for categorical/discrete values.
# Example:
#        A continuous feature like radius_mean can be converted into values:
#            0, 1, 2, 3
#   The code uses percentiles so each bin has a reasonable number of examples.
# -----------------------------------------------------------------------------

def discretize_numeric_features(X, bins=4):
    

    X_discrete = np.zeros_like(X, dtype=int)

    for col in range(X.shape[1]):
        values = X[:, col]

        # Create percentile cut points.
        # Example for bins=4:
        #   25th percentile, 50th percentile, 75th percentile
        cut_points = np.percentile(values, np.linspace(0, 100, bins + 1)[1:-1])

        # np.digitize assigns each value to a bin.
        X_discrete[:, col] = np.digitize(values, cut_points)

    return X_discrete


# =============================================================================
# SECTION 3 - ENTROPY / INFORMATION GAIN
# =============================================================================

# -----------------------------------------------------------------------------
# ENTROPY
# Entropy measures impurity/disorder.
# Formula:  H(S) = - Σ p(x) log2 p(x)
# Lower entropy:  More pure
# Higher entropy:  More mixed
# Examples:
# Pure node:
#   [all class 3]
#   entropy = 0
# Mixed node:
#   [many different classes]
#   entropy = high
# -----------------------------------------------------------------------------

def entropy(y):

    # Count occurrences of each class
    classes, counts = np.unique(y, return_counts=True)

    # Convert counts into probabilities
    probabilities = counts / len(y)

    # Compute entropy
    ent = -np.sum(probabilities * np.log2(probabilities))

    # Handle NaNs
    ent = np.nan_to_num(ent, nan=0.0)

    return ent

# -----------------------------------------------------------------------------
# SPLIT INFO
# Used in C4.5 gain ratio formula.
# Formula:  SplitInfo = - Σ (|Si| / |S|) log2(|Si| / |S|)
# This penalizes splits that create too many tiny branches.
# -----------------------------------------------------------------------------

def split_info(subsets, total_size):

    values = []

    for subset in subsets:
        proportion = len(subset) / total_size

        if proportion > 0:
            values.append(-proportion * np.log2(proportion))

    return np.sum(values)

# -----------------------------------------------------------------------------
# GAIN RATIO
# C4.5 uses: GainRatio = InformationGain / SplitInfo
# If SplitInfo = 0:
#   GainRatio = 0
# -----------------------------------------------------------------------------

def information_gain_and_ratio(X_column, y):
    """Return information gain, split information, and gain ratio.

    C4.5 does not select the attribute with the highest gain ratio from all
    available attributes. It first calculates information gain for every
    candidate attribute, computes the average information gain, discards
    attributes below that average, and only then chooses the highest gain
    ratio from the remaining attributes.
    """
    total_entropy = entropy(y)
    values = np.unique(X_column)

    weighted_entropy = 0.0
    subsets = []

    for value in values:
        subset_y = y[X_column == value]
        subsets.append(subset_y)

        weight = len(subset_y) / len(y)
        weighted_entropy += weight * entropy(subset_y)

    information_gain = total_entropy - weighted_entropy
    splitinfo = split_info(subsets, len(y))

    # C4.5 special case: gain ratio is zero when split information is zero.
    if splitinfo == 0.0:
        gainratio = 0.0
    else:
        gainratio = information_gain / splitinfo

    return information_gain, splitinfo, gainratio


def information_gain(X_column, y):
    """Compute information gain for one candidate attribute."""
    gain, _, _ = information_gain_and_ratio(X_column, y)
    return gain


def gain_ratio(X_column, y):
    """Compute gain ratio for one candidate attribute."""
    _, _, ratio = information_gain_and_ratio(X_column, y)
    return ratio

# =============================================================================
# SECTION 4 - DECISION TREE NODE
# =============================================================================

# -----------------------------------------------------------------------------
# TREE NODE
# Each node stores:
# feature: Which attribute/pixel we split on
# children: Dictionary mapping feature values to child nodes
# prediction: Majority class at this node
# is_leaf: True if node is terminal
# -----------------------------------------------------------------------------

class TreeNode:

    def __init__(self):
        self.feature = None
        self.children = {}
        self.prediction = None
        self.is_leaf = False

# =============================================================================
# SECTION 5 - C4.5 DECISION TREE
#  For a normal single decision tree:
#       random_features = None
#   For random forest trees:
#       random_features = number of random features to consider at each split
# =============================================================================

class C45DecisionTree:

    def __init__(self,
                 max_depth=15,
                 min_samples_split=5,
                 random_features=None):

        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.random_features = random_features
        self.root = None

    # -------------------------------------------------------------------------
    # TRAIN TREE
    # -------------------------------------------------------------------------

    def fit(self, X, y):

        features = np.arange(X.shape[1])
        self.root = self.build_tree(X, y, features, depth=0)

    # -------------------------------------------------------------------------
    # BUILD TREE RECURSIVELY
    # The tree recursively splits the dataset.
    # Stopping conditions:
    #   1. All labels identical
    #   2. No features left
    #   3. Max depth reached
    #   4. Too few examples
    # -------------------------------------------------------------------------

    def build_tree(self, X, y, features, depth):

        node = TreeNode()

        # Majority class prediction
        node.prediction = self.majority_class(y)

        # STOP CONDITION 1: if all examples have the same class.
        if len(np.unique(y)) == 1:
            node.is_leaf = True
            return node

        # STOP CONDITION 2: if there are no features left.
        if len(features) == 0:
            node.is_leaf = True
            return node

        # STOP CONDITION 3: if max depth is reached.
        if depth >= self.max_depth:
            node.is_leaf = True
            return node

        # STOP CONDITION 4: if too few samples are available.
        if len(y) < self.min_samples_split:
            node.is_leaf = True
            return node

        # ---------------------------------------------------------------------
        # RANDOM FEATURE SUBSET
        # Used ONLY for Random Forest
        # ---------------------------------------------------------------------

        candidate_features = features

        if self.random_features is not None:
            subset_size = min(self.random_features, len(features))
            candidate_features = np.random.choice(
                features,
                subset_size,
                replace=False
            )

        # ---------------------------------------------------------------------
        # FIND BEST FEATURE
        # ---------------------------------------------------------------------

        # C4.5 attribute selection is a two-stage process:
        #   1. Calculate information gain for every candidate feature.
        #   2. Calculate the average information gain and eliminate features
        #      whose information gain is below that average.
        #   3. Among the remaining features, select the feature with the
        #      highest gain ratio.
        #
        # This filter prevents an attribute with very small information gain
        # and very small split information from receiving an artificially high
        # gain ratio.
        feature_statistics = []

        for feature in candidate_features:
            info_gain, splitinfo, ratio = information_gain_and_ratio(
                X[:, feature], y
            )
            feature_statistics.append(
                (feature, info_gain, splitinfo, ratio)
            )

        positive_gains = [
            info_gain
            for _, info_gain, _, _ in feature_statistics
            if info_gain > 0.0
        ]

        # If every candidate has zero information gain, no useful split exists.
        if not positive_gains:
            node.is_leaf = True
            return node

        average_information_gain = float(np.mean(positive_gains))

        eligible_features = [
            (feature, info_gain, ratio)
            for feature, info_gain, _, ratio in feature_statistics
            if info_gain >= average_information_gain and ratio > 0.0
        ]

        # Numerical edge cases can leave no eligible feature. Falling back to
        # the largest positive information gain is safer than creating an
        # invalid split and still preserves deterministic behavior.
        if eligible_features:
            best_feature, best_info_gain, best_gain_ratio = max(
                eligible_features,
                key=lambda item: (item[2], item[1], -int(item[0]))
            )
        else:
            fallback = [
                (feature, info_gain, ratio)
                for feature, info_gain, _, ratio in feature_statistics
                if info_gain > 0.0
            ]
            best_feature, best_info_gain, best_gain_ratio = max(
                fallback,
                key=lambda item: (item[1], item[2], -int(item[0]))
            )

        if best_feature is None or best_info_gain <= 0.0:
            node.is_leaf = True
            return node

        node.feature = best_feature

        # ---------------------------------------------------------------------
        # SPLIT DATA
        # ---------------------------------------------------------------------

        values = np.unique(X[:, best_feature])
        remaining_features = features[features != best_feature]

        for value in values:
            mask = X[:, best_feature] == value

            child_X = X[mask]
            child_y = y[mask]

            child_node = self.build_tree(
                child_X,
                child_y,
                remaining_features,
                depth + 1
            )

            node.children[value] = child_node

        return node

    # -------------------------------------------------------------------------
    # MAJORITY CLASS
    # Return the most common class label.
    # -------------------------------------------------------------------------

    def majority_class(self, y):

        values, counts = np.unique(y, return_counts=True)
        return values[np.argmax(counts)]

    # -------------------------------------------------------------------------
    # PREDICT SINGLE EXAMPLE
    # Predict one example by walking through the tree.
    # -------------------------------------------------------------------------

    def predict_one(self, x, node):

        # If leaf:
        # return stored prediction
        if node.is_leaf:
            return node.prediction

        feature_value = x[node.feature]

        # If branch exists:
        if feature_value in node.children:
            return self.predict_one(
                x,
                node.children[feature_value]
            )

        # If unseen branch:
        return node.prediction

    # -------------------------------------------------------------------------
    # PREDICT MULTIPLE EXAMPLES
    # -------------------------------------------------------------------------

    def predict(self, X):

        predictions = []

        for x in X:
            predictions.append(
                self.predict_one(x, self.root)
            )

        return np.array(predictions)


# =============================================================================
# SECTION 6 - RANDOM FOREST
# Random Forest classifier made from many C4.5 decision trees.
#   Randomness comes from:
#       1. Bootstrap sampling
#       2. Random feature subsets at each split
# =============================================================================

class RandomForest:

    def __init__(self,
                 n_trees=25,
                 max_depth=15,
                 min_samples_split=5,
                 random_features=50,
                 bootstrap_size=None):

        self.n_trees = n_trees
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.random_features = random_features
        self.bootstrap_size = bootstrap_size
        self.trees = []

    # -------------------------------------------------------------------------
    # BOOTSTRAP SAMPLE
    # Randomly sample WITH replacement.
    # Some examples repeat.
    # Some are omitted.
    # This introduces randomness.
    # -------------------------------------------------------------------------

    def bootstrap_sample(self, X, y):

        n_samples = len(X)
        size = self.bootstrap_size or n_samples

        indices = np.random.choice(
            n_samples,
            size,
            replace=True
        )

        return X[indices], y[indices]

    # -------------------------------------------------------------------------
    # TRAIN FOREST
    # -------------------------------------------------------------------------

    def fit(self, X, y):

        self.trees = []

        for i in range(self.n_trees):
            print(f"Training tree {i+1}/{self.n_trees}")

            sample_X, sample_y = self.bootstrap_sample(X, y)

            tree = C45DecisionTree(
                max_depth=self.max_depth,
                min_samples_split=self.min_samples_split,
                random_features=self.random_features
            )

            tree.fit(sample_X, sample_y)
            self.trees.append(tree)

    # -------------------------------------------------------------------------
    # PREDICT USING MAJORITY VOTING
    # Every tree votes.
    #
    # Final prediction:
    #   class with most votes
    # -------------------------------------------------------------------------

    def predict(self, X):

        tree_predictions = []

        for tree in self.trees:
            tree_predictions.append(tree.predict(X))

        tree_predictions = np.array(tree_predictions)

        final_predictions = []

        for i in range(X.shape[0]):
            votes = tree_predictions[:, i]
            values, counts = np.unique(votes, return_counts=True)
            final_predictions.append(values[np.argmax(counts)])

        return np.array(final_predictions)


# =============================================================================
# SECTION 7 - ADABOOST
# =============================================================================

# -----------------------------------------------------------------------------
# Decision stump:
# very weak learner
# AdaBoost combines many weak learners into one strong classifier.
# -----------------------------------------------------------------------------

class DecisionStump:

    def __init__(self):
        self.feature = None
        self.threshold = None
        self.polarity = 1
        self.alpha = 0

    def predict(self, X):

        n_samples = X.shape[0]
        predictions = np.ones(n_samples)

        if self.polarity == 1:
            predictions[X[:, self.feature] < self.threshold] = -1
        else:
            predictions[X[:, self.feature] >= self.threshold] = -1

        return predictions


# -----------------------------------------------------------------------------
# AdaBoost Binary Classifier
# -----------------------------------------------------------------------------

class AdaBoostBinary:

    def __init__(self, n_estimators=25):
        self.n_estimators = n_estimators
        self.stumps = []

    # Train AdaBoost.

    # Each round:
    #    1. Find best weak stump
    #    2. Compute stump weight alpha
    #    3. Increase weights of misclassified examples
    #    4. Decrease weights of correctly classified examples

    def fit(self, X, y):

        n_samples, n_features = X.shape

        # Initialize equal weights
        weights = np.full(n_samples, 1 / n_samples)
        self.stumps = []

        for estimator in range(self.n_estimators):
            print(f"Training AdaBoost stump {estimator + 1}/{self.n_estimators}")

            stump = DecisionStump()
            min_error = float('inf')

            # Search all features
            for feature in range(n_features):
                feature_values = np.unique(X[:, feature])

                for threshold in feature_values:
                    predictions = np.ones(n_samples)
                    predictions[X[:, feature] < threshold] = -1

                    # Weighted error
                    error = np.sum(
                        weights[y != predictions]
                    )
                    polarity = 1

                    # Flip if worse than random
                    if error > 0.5:
                        error = 1 - error
                        polarity = -1

                    if error < min_error:
                        stump.feature = feature
                        stump.threshold = threshold
                        stump.polarity = polarity
                        min_error = error

            EPS = 1e-10

            # Alpha controls influence of stump
            stump.alpha = 0.5 * np.log(
                (1 - min_error + EPS) /
                (min_error + EPS)
            )

            predictions = stump.predict(X)

            # Update weights
            weights *= np.exp(
                -stump.alpha * y * predictions
            )

            # Normalize
            weights /= np.sum(weights)
        
            self.stumps.append(stump)

    # Return raw AdaBoost confidence scores.
    def predict_scores(self, X):

        scores = np.zeros(X.shape[0])

        for stump in self.stumps:
            scores += stump.alpha * stump.predict(X)

        return scores
    
    # Convert scores into class labels.
    def predict(self, X):
        
        scores = self.predict_scores(X)
        return np.where(scores >= 0, 1, -1)



# -----------------------------------------------------------------------------
# ONE VS REST ADABOOST
# Since MNIST has 10 classes: 0-9
# We train: 10 binary classifiers
# Example:
#   Model 0:
#       0 vs not-0
#   Model 1:
#       1 vs not-1
# -----------------------------------------------------------------------------

class AdaBoostOVR:

    def __init__(self, n_estimators=25):
        self.n_estimators = n_estimators
        self.models = {}

    # Train one binary AdaBoost model for each class.
    def fit(self, X, y):

        self.models = {}
        classes = np.unique(y)

        for cls in classes:

            print(f"Training AdaBoost for class {cls}")

            binary_y = np.where(y == cls, 1, -1)

            model = AdaBoostBinary(
                n_estimators=self.n_estimators
            )

            model.fit(X, binary_y)
            self.models[cls] = model

    #  Choose the class with the highest AdaBoost score.
    def predict(self, X):

        scores = []
        classes = sorted(self.models.keys())

        for cls in classes:
            model_scores = self.models[cls].predict_scores(X)
            scores.append(model_scores)

        scores = np.array(scores)
        predictions = np.argmax(scores, axis=0)

        return predictions


# =============================================================================
# SECTION 8 - EVALUATION FUNCTIONS
# =============================================================================

# Compute classification accuracy.
def accuracy(y_true, y_pred):

    return np.mean(y_true == y_pred)


# -----------------------------------------------------------------------------
# CONFUSION MATRIX
# Rows: actual class
# Columns: predicted class
# -----------------------------------------------------------------------------

def confusion_matrix(y_true, y_pred, num_classes):

    matrix = np.zeros((num_classes, num_classes), dtype=int)

    for actual, predicted in zip(y_true, y_pred):
        matrix[actual][predicted] += 1

    return matrix


# =============================================================================
# SECTION 9 -  CANCER DATASET LOADING
#
#   Load the Kaggle Breast Cancer Wisconsin dataset as the extra dataset.
#
#   Expected file:
#       data.csv
#
#   Standard Kaggle columns:
#       column 0 = id
#       column 1 = diagnosis
#       columns 2 through second-to-last = numeric tumor features
#       final column = usually empty, named Unnamed: 32
#
#   Prediction target:
#       diagnosis
#   
#   Encoding:
#       M = malignant = 1
#       B = benign = 0
# =============================================================================
def load_extra_dataset(filename):
    raw = np.genfromtxt(filename, delimiter=",", dtype=str, skip_header=1)

    # Column 1 is the label we are predicting.
    y_text = raw[:, 1]
    # Convert labels to numbers.
    y = np.where(y_text == "M", 1, 0)

    # Use columns 2 through the second-to-last column as features.
    # This removes:
    #   id
    #   diagnosis
    X = raw[:, 2:]

    if X[0, -1] == "" or X[0, -1].lower() == "nan":
        X = X[:, :-1]

    X = X.astype(float)

    return X, y

# =============================================================================
# SECTION 10 - PRINTING
# =============================================================================

def print_results(name, y_true, y_pred, num_classes, start_time):
    """
    Print accuracy, runtime, and confusion matrix.
    """

    end_time = time.time()

    print("\n----------------------------------------")
    print(name)
    print("----------------------------------------")
    print(f"Accuracy: {accuracy(y_true, y_pred):.4f}")
    print(f"Runtime: {end_time - start_time:.2f} seconds")
    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred, num_classes))
    print("----------------------------------------\n")


# =============================================================================
# SECTION 11 - RUN EVERYTHING
# =============================================================================

@save_print_output("running_everything_output.txt")
def running_everything():

    start_total = time.time()

    # -------------------------------------------------------------------------
    # LOAD MNIST
    # -------------------------------------------------------------------------

    print("\nLoading MNIST dataset...\n")

    X_train = load_images("train-images-idx3-ubyte")
    y_train = load_labels("train-labels-idx1-ubyte")

    X_test = load_images("t10k-images-idx3-ubyte")
    y_test = load_labels("t10k-labels-idx1-ubyte")

    print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
    plt.imshow(X_train[0], cmap='gray')
    plt.title("An image of " + str(y_train[0]))
    plt.show()

    # -------------------------------------------------------------------------
    # PREPROCESS
    # -------------------------------------------------------------------------

    print("Binarizing images...")

    X_train = binarize_images(X_train)

    X_test = binarize_images(X_test)

    print("Flattening images...")

    X_train = flatten_images(X_train)

    X_test = flatten_images(X_test)

    # -------------------------------------------------------------------------
    # SMALL SUBSET
    # IMPORTANT:
    # Full MNIST can take a VERY long time.
    # Start small for debugging.
    # Then increase later.
    # -------------------------------------------------------------------------

    train_subset = 40000
    test_subset = 5000

    X_train_small = X_train[:train_subset]
    y_train_small = y_train[:train_subset]

    X_test_small = X_test[:test_subset]
    y_test_small = y_test[:test_subset]

    # =============================================================================
    # SINGLE C4.5 TREE
    # =============================================================================

    print("\n==============================")
    print("TRAINING SINGLE C4.5 TREE")
    print("==============================\n")

    start = time.time()

    tree = C45DecisionTree(
        max_depth=40,
        min_samples_split=2
    )

    tree.fit(X_train_small, y_train_small)

    predictions = tree.predict(X_test_small)

    acc = accuracy(y_test_small, predictions)

    end = time.time()

    print(f"\nC4.5 Accuracy: {acc:.4f}")
    print(f"Execution Time: {end - start:.2f} seconds")

    matrix = confusion_matrix(
        y_test_small,
        predictions,
        10
    )

    print("\nConfusion Matrix:")
    print(matrix)

    # =============================================================================
    # RANDOM FOREST
    # =============================================================================

    print("\n==============================")
    print("TRAINING RANDOM FOREST")
    print("==============================\n")

    start = time.time()

    forest = RandomForest(
        n_trees=100,
        max_depth=50,
        random_features=25
    )

    forest.fit(X_train_small, y_train_small)

    predictions = forest.predict(X_test_small)

    acc = accuracy(y_test_small, predictions)

    end = time.time()

    print(f"\nRandom Forest Accuracy: {acc:.4f}")
    print(f"Execution Time: {end - start:.2f} seconds")

    matrix = confusion_matrix(
        y_test_small,
        predictions,
        10
    )

    print("\nConfusion Matrix:")
    print(matrix)

    # =============================================================================
    # ADABOOST OVR
    # =============================================================================

    print("\n==============================")
    print("TRAINING ADABOOST OVR")
    print("==============================\n")

    start = time.time()

    booster = AdaBoostOVR(
        n_estimators=100
    )

    booster.fit(X_train_small, y_train_small)

    predictions = booster.predict(X_test_small)

    acc = accuracy(y_test_small, predictions)

    end = time.time()

    print(f"\nAdaBoost OvR Accuracy: {acc:.4f}")
    print(f"Execution Time: {end - start:.2f} seconds")

    matrix = confusion_matrix(
        y_test_small,
        predictions,
        10
    )

    print("\nConfusion Matrix:")
    print(matrix)

    # =========================================================================
    # EXTRA DATASET
    # =========================================================================

    if os.path.exists("data.csv"):

        print("\n==============================")
        print("EXTRA DATASET")
        print("==============================\n")

        X_bc, y_bc = load_extra_dataset("data.csv")

        # Discretize numeric data for C4.5.
        X_bc = discretize_numeric_features(X_bc, bins=4)

        split_index = int(0.8 * len(X_bc))

        X_bc_train = X_bc[:split_index]
        y_bc_train = y_bc[:split_index]

        X_bc_test = X_bc[split_index:]
        y_bc_test = y_bc[split_index:]

        # ---------------------------------------------------------------------
        # EXTRA DATASET C4.5
        # ---------------------------------------------------------------------

        start = time.time()

        bc_tree = C45DecisionTree(
            max_depth=8,
            min_samples_split=3
        )

        bc_tree.fit(X_bc_train, y_bc_train)

        pred_bc_tree = bc_tree.predict(X_bc_test)
        
        end = time.time()
        execution = end - start
    
        print_results(
            "Extra Dataset C4.5 Decision Tree",
            y_bc_test,
            pred_bc_tree,
            2,
            execution
        )

        # ---------------------------------------------------------------------
        # EXTRA DATASET RANDOM FOREST
        # ---------------------------------------------------------------------

        start = time.time()

        bc_forest = RandomForest(
            n_trees=25,
            max_depth=10,
            min_samples_split=3,
            random_features=5
        )

        bc_forest.fit(X_bc_train, y_bc_train)

        pred_bc_forest = bc_forest.predict(X_bc_test)

        end = time.time()
        execution = end - start
        
        print_results(
            "Extra Dataset Random Forest",
            y_bc_test,
            pred_bc_forest,
            2,
            execution
        )

        # ---------------------------------------------------------------------
        # EXTRA DATASET ADABOOST
        # ---------------------------------------------------------------------

        start = time.time()

        bc_boost = AdaBoostBinary(
            n_estimators=20
        )

        # AdaBoostBinary needs labels as +1 and -1.
        y_bc_train_binary = np.where(y_bc_train == 1, 1, -1)

        bc_boost.fit(X_bc_train, y_bc_train_binary)

        pred_bc_boost_binary = bc_boost.predict(X_bc_test)

        # Convert predictions back:
        #   +1 -> 1
        #   -1 -> 0
        pred_bc_boost = np.where(pred_bc_boost_binary == 1, 1, 0)

        end = time.time()
        execution = end - start

        print_results(
            "Extra Dataset AdaBoost",
            y_bc_test,
            pred_bc_boost,
            2,
            execution
        )

    else:
        print("\ndata.csv was not found. Skipping Extra Dataset experiments.\n")

    

    print("\n========================================")
    print("ALL EXPERIMENTS FINISHED")
    print("========================================")

# =============================================================================
# SECTION 11 - TEST FUNCTIONS AND MAIN EXECUTION
# =============================================================================

def split_data(X, y, train_ratio=0.8):
    np.random.seed(1)
    indices = np.arange(len(X))
    np.random.shuffle(indices)

    X = X[indices]
    y = y[indices]

    split_index = int(train_ratio * len(X))

    return X[:split_index], y[:split_index], X[split_index:], y[split_index:]


def run_and_print(name, model, X_train, y_train, X_test, y_test, num_classes):
    print("\n==============================")
    print(name)
    print("==============================")

    start = time.time()

    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    end = time.time()

    print(f"Accuracy: {accuracy(y_test, predictions):.4f}")
    print(f"Runtime: {end - start:.2f} seconds")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions, num_classes))

    return accuracy(y_test, predictions), end - start


def run_adaboost_binary_test(name, X_train, y_train, X_test, y_test, n_estimators):
    print("\n==============================")
    print(name)
    print("==============================")

    start = time.time()

    y_train_binary = np.where(y_train == 1, 1, -1)

    model = AdaBoostBinary(n_estimators=n_estimators)
    model.fit(X_train, y_train_binary)

    pred_binary = model.predict(X_test)
    predictions = np.where(pred_binary == 1, 1, 0)

    end = time.time()

    print(f"Accuracy: {accuracy(y_test, predictions):.4f}")
    print(f"Runtime: {end - start:.2f} seconds")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions, 2))

    return accuracy(y_test, predictions), end - start


def extra_dataset_tests():
    print("\n\nEXTRA DATASET TESTS")

    X, y = load_extra_dataset("data.csv")
    X = discretize_numeric_features(X, bins=4)

    X_train, y_train, X_test, y_test = split_data(X, y)

    print("\nFULL ALGORITHM COMPARISON")

    run_and_print(
        "Extra Dataset C4.5",
        C45DecisionTree(max_depth=8, min_samples_split=3),
        X_train, y_train, X_test, y_test, 2
    )

    run_and_print(
        "Extra Dataset Random Forest",
        RandomForest(n_trees=25, max_depth=10, min_samples_split=3, random_features=5),
        X_train, y_train, X_test, y_test, 2
    )

    run_adaboost_binary_test(
        "Extra Dataset AdaBoost",
        X_train, y_train, X_test, y_test,
        n_estimators=20
    )

    print("\nC4.5 MAX DEPTH TESTS")
    for depth in [2, 4, 6, 8, 10, 12]:
        run_and_print(
            f"C4.5 max_depth={depth}",
            C45DecisionTree(max_depth=depth, min_samples_split=3),
            X_train, y_train, X_test, y_test, 2
        )

    print("\nC4.5 MIN SAMPLES SPLIT TESTS")
    for split in [2, 3, 5, 10, 15]:
        run_and_print(
            f"C4.5 min_samples_split={split}",
            C45DecisionTree(max_depth=8, min_samples_split=split),
            X_train, y_train, X_test, y_test, 2
        )

    print("\nRANDOM FOREST NUMBER OF TREES TESTS")
    for trees in [5, 10, 25, 50]:
        run_and_print(
            f"Random Forest n_trees={trees}",
            RandomForest(n_trees=trees, max_depth=10, min_samples_split=3, random_features=5),
            X_train, y_train, X_test, y_test, 2
        )

    print("\nRANDOM FOREST RANDOM FEATURES TESTS")
    for features in [2, 4, 6, 8, 10]:
        run_and_print(
            f"Random Forest random_features={features}",
            RandomForest(n_trees=25, max_depth=10, min_samples_split=3, random_features=features),
            X_train, y_train, X_test, y_test, 2
        )

    print("\nADABOOST ESTIMATOR TESTS")
    for estimators in [5, 10, 20, 30, 50]:
        run_adaboost_binary_test(
            f"AdaBoost n_estimators={estimators}",
            X_train, y_train, X_test, y_test,
            n_estimators=estimators
        )


def mnist_tests():
    print("\n\nMNIST DATASET TESTS")

    X_train = load_images("train-images-idx3-ubyte")
    y_train = load_labels("train-labels-idx1-ubyte")

    X_test = load_images("t10k-images-idx3-ubyte")
    y_test = load_labels("t10k-labels-idx1-ubyte")

    X_train = flatten_images(binarize_images(X_train))
    X_test = flatten_images(binarize_images(X_test))

    X_train = X_train[:5000]
    y_train = y_train[:5000]

    X_test = X_test[:1000]
    y_test = y_test[:1000]

    print("\nFULL ALGORITHM COMPARISON")

    run_and_print(
        "MNIST C4.5",
        C45DecisionTree(max_depth=15, min_samples_split=5),
        X_train, y_train, X_test, y_test, 10
    )

    run_and_print(
        "MNIST Random Forest",
        RandomForest(n_trees=25, max_depth=15, min_samples_split=5, random_features=50),
        X_train, y_train, X_test, y_test, 10
    )

    run_and_print(
        "MNIST AdaBoost One-vs-Rest",
        AdaBoostOVR(n_estimators=10),
        X_train, y_train, X_test, y_test, 10
    )

    print("\nMNIST C4.5 MAX DEPTH TESTS")
    for depth in [5, 10, 15, 20]:
        run_and_print(
            f"MNIST C4.5 max_depth={depth}",
            C45DecisionTree(max_depth=depth, min_samples_split=5),
            X_train, y_train, X_test, y_test, 10
        )

    print("\nMNIST RANDOM FOREST NUMBER OF TREES TESTS")
    for trees in [5, 10, 25, 50]:
        run_and_print(
            f"MNIST Random Forest n_trees={trees}",
            RandomForest(n_trees=trees, max_depth=15, min_samples_split=5, random_features=50),
            X_train, y_train, X_test, y_test, 10
        )

    print("\nMNIST RANDOM FOREST RANDOM FEATURES TESTS")
    for features in [25, 50, 75, 100]:
        run_and_print(
            f"MNIST Random Forest random_features={features}",
            RandomForest(n_trees=25, max_depth=15, min_samples_split=5, random_features=features),
            X_train, y_train, X_test, y_test, 10
        )

    print("\nMNIST ADABOOST ESTIMATOR TESTS")
    for estimators in [5, 10, 15]:
        run_and_print(
            f"MNIST AdaBoost OvR n_estimators={estimators}",
            AdaBoostOVR(n_estimators=estimators),
            X_train, y_train, X_test, y_test, 10
        )

@save_print_output("running_test_output.txt")
def running_test():
    total_start = time.time()

    if os.path.exists("data.csv"):
        extra_dataset_tests()
    else:
        print("data.csv not found.")

    if (
        os.path.exists("train-images-idx3-ubyte") and
        os.path.exists("train-labels-idx1-ubyte") and
        os.path.exists("t10k-images-idx3-ubyte") and
        os.path.exists("t10k-labels-idx1-ubyte")
    ):
        mnist_tests()
    else:
        print("MNIST files not found.")

    total_end = time.time()

    print("\n========================================")
    print("ALL TESTS FINISHED")
    print("========================================")
    print(f"Total runtime: {total_end - total_start:.2f} seconds")


if __name__ == "__main__":
#    running_everything()
   running_test()
    